### Overview

- Testing Machine Learning models on the original 30-sec 1000 file dataset

- Models Used
    - RandomForest - Ensemble Model that uses Bagging
    - XGBoost - Ensemble Model that uses boosting (This should perform best)

## Import Libraries

In [1]:
#Import Standard Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier

## Data Preprocessing

In [2]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
# Get Data Ready
data_file = "Data/features_30_sec.csv" 
music_data = pd.read_csv(data_file)
music_data;

In [4]:
# Remove unnecessary Fields
music_data.drop(labels=["filename","length"],inplace=True, axis=1)
music_data;

In [5]:
label_mappings = dict(enumerate(music_data['label'].unique()))
label_mappings

{0: 'blues',
 1: 'classical',
 2: 'country',
 3: 'disco',
 4: 'hiphop',
 5: 'jazz',
 6: 'metal',
 7: 'pop',
 8: 'reggae',
 9: 'rock'}

In [6]:
#Converting Label Column to Numerical Field
for k, v in label_mappings.items():
    music_data.loc[(music_data['label'] == v),'label_code'] = k
    
music_data

,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,rolloff_var,...,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label,label_code
0,0.350088,0.088757,0.130228,0.002827,1784.165850,129774.064525,2002.449060,85882.761315,3805.839606,9.015054e+05,...,-1.690215,36.524071,-0.408979,41.597103,-2.303523,55.062923,1.221291,46.936035,blues,0.0
1,0.340914,0.094980,0.095948,0.002373,1530.176679,375850.073649,2039.036516,213843.755497,3550.522098,2.977893e+06,...,-0.731125,60.314529,0.295073,48.120598,-0.283518,51.106190,0.531217,45.786282,blues,0.0
2,0.363637,0.085275,0.175570,0.002746,1552.811865,156467.643368,1747.702312,76254.192257,3042.260232,7.840345e+05,...,-7.729093,47.639427,-1.816407,52.382141,-3.439720,46.639660,-2.231258,30.573025,blues,0.0
3,0.404785,0.093999,0.141093,0.006346,1070.106615,184355.942417,1596.412872,166441.494769,2184.745799,1.493194e+06,...,-3.319597,50.206673,0.636965,37.319130,-0.619121,37.259739,-3.407448,31.949339,blues,0.0
4,0.308526,0.087841,0.091529,0.002303,1835.004266,343399.939274,1748.172116,88445.209036,3579.757627,1.572978e+06,...,-5.454034,75.269707,-0.916874,53.613918,-4.404827,62.910812,-11.703234,55.195160,blues,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.352063,0.080487,0.079486,0.000345,2008.149458,282174.689224,2106.541053,88609.749506,4253.557033,1.222421e+06,...,-13.289984,41.754955,2.484145,36.778877,-6.713265,54.866825,-1.193787,49.950665,rock,9.0
996,0.398687,0.075086,0.076458,0.000588,2006.843354,182114.709510,2068.942009,82426.016726,4149.338328,1.046621e+06,...,-10.848309,39.395096,1.881229,32.010040,-7.461491,39.196327,-2.795338,31.773624,rock,9.0
997,0.432142,0.075268,0.081651,0.000322,2077.526598,231657.968040,1927.293153,74717.124394,4031.405321,8.042154e+05,...,-12.845291,36.367264,3.440978,36.001110,-12.588070,42.502201,-2.106337,29.865515,rock,9.0
998,0.362485,0.091506,0.083860,0.001211,1398.699344,240318.731073,1818.450280,109090.207161,3015.631004,1.332712e+06,...,-4.416050,43.583942,1.556207,34.331261,-5.041897,47.227180,-3.590644,41.299088,rock,9.0
999,0.358401,0.085884,0.054454,0.000336,1609.795082,422203.216152,1797.213044,120115.632927,3246.908930,1.753476e+06,...,-7.069775,73.760391,0.028346,76.504326,-2.025783,72.189316,1.155239,49.662510,rock,9.0

In [7]:
music_data[['label','label_code']]

     label  label_code
0    blues         0.0
1    blues         0.0
2    blues         0.0
3    blues         0.0
4    blues         0.0
..     ...         ...
995   rock         9.0
996   rock         9.0
997   rock         9.0
998   rock         9.0
999   rock         9.0

[1000 rows x 2 columns]

In [8]:
# Split data into train/test datasets
from sklearn.model_selection import train_test_split

## Create Models

### Random Forest (72% Accuracy)

#### Models Ran
 - Accuracy (n_estimators = 1000, criterion = gini) = 0.7133333333333334 - Best

 - Classification Report for best model
              precision    recall  f1-score   support

       blues       0.89      0.75      0.81        32
   classical       0.90      0.85      0.88        33
     country       0.67      0.67      0.67        30
       disco       0.70      0.58      0.63        33
      hiphop       0.69      0.65      0.67        31
        jazz       0.77      0.88      0.82        26
       metal       0.68      0.92      0.78        25
         pop       0.74      0.82      0.78        28
      reggae       0.59      0.61      0.60        33
        rock       0.52      0.48      0.50        29

    accuracy                           0.71       300
   macro avg       0.71      0.72      0.71       300
weighted avg       0.72      0.71      0.71       300

In [17]:
# Create Random Forest Model
ml_randomforest = RandomForestClassifier(n_estimators=1000)

# Train Random Forest
# Create X (Features)
rfX = music_data.drop(["label", "label_code"], axis=1)

# Create Y (Labels)
rfY = music_data['label']

rfX_train, rfX_test, rfY_train, rfY_test = train_test_split(rfX, rfY, test_size=0.3)
ml_randomforest.fit(rfX_train, rfY_train)

ml_randomforest.score(rfX_test, rfY_test)

0.71

In [13]:
rf_preds = ml_randomforest.predict(rfX_test)

print(classification_report(rfY_test, rf_preds))

              precision    recall  f1-score   support

       blues       0.89      0.75      0.81        32
   classical       0.90      0.85      0.88        33
     country       0.67      0.67      0.67        30
       disco       0.70      0.58      0.63        33
      hiphop       0.69      0.65      0.67        31
        jazz       0.77      0.88      0.82        26
       metal       0.68      0.92      0.78        25
         pop       0.74      0.82      0.78        28
      reggae       0.59      0.61      0.60        33
        rock       0.52      0.48      0.50        29

    accuracy                           0.71       300
   macro avg       0.71      0.72      0.71       300
weighted avg       0.72      0.71      0.71       300

### XGBoost (73.67% Accuracy)

#### Key for XGBoost Labels
 0.0 (blues)
 1.0 (classical)
 2.0 (country)
 3.0 (disco)
 4.0 (hiphop)
 5.0 (jazz)
 6.0 (metal)
 7.0 (pop)
 8.0 (reggae)
 9.0 (rock)
 

#### Models Ran
- n_estimators=1000, max_depth=6, learning_rate=0.1: 0.7366666666666667 - Best

Best Classification Report
              precision    recall  f1-score   support

         0.0       0.71      0.88      0.79        25
         1.0       0.93      0.87      0.90        30
         2.0       0.68      0.70      0.69        27
         3.0       0.58      0.58      0.58        26
         4.0       0.76      0.65      0.70        34
         5.0       0.65      0.92      0.76        24
         6.0       0.86      0.89      0.87        35
         7.0       0.91      0.83      0.87        35
         8.0       0.67      0.71      0.69        28
         9.0       0.58      0.42      0.48        36

    accuracy                           0.74       300
   macro avg       0.73      0.74      0.73       300
weighted avg       0.74      0.74      0.73       300

In [18]:
# Create and train XGBoost model w/ default parameters
ml_xgboost = xgb.XGBClassifier(n_estimators=1000, max_depth=6, learning_rate=0.3)

# Train XGBoost - Looks like XGBoost doesn't work with categorical data only numerical
# Create X (Features)
xgbX = music_data.drop(["label", "label_code"], axis=1)

# Create Y (Labels)
xgbY = music_data['label_code']

xgbX_train, xgbX_test, xgbY_train, xgbY_test = train_test_split(xgbX, xgbY, test_size=0.3)
ml_xgboost.fit(xgbX_train, xgbY_train)

xgb_preds = ml_xgboost.predict(xgbX_test)

ml_xgboost.score(xgbX_test, xgbY_test)

0.7366666666666667

In [19]:
print(classification_report(xgbY_test, xgb_preds))

              precision    recall  f1-score   support

         0.0       0.71      0.88      0.79        25
         1.0       0.93      0.87      0.90        30
         2.0       0.68      0.70      0.69        27
         3.0       0.58      0.58      0.58        26
         4.0       0.76      0.65      0.70        34
         5.0       0.65      0.92      0.76        24
         6.0       0.86      0.89      0.87        35
         7.0       0.91      0.83      0.87        35
         8.0       0.67      0.71      0.69        28
         9.0       0.58      0.42      0.48        36

    accuracy                           0.74       300
   macro avg       0.73      0.74      0.73       300
weighted avg       0.74      0.74      0.73       300