### Overview

- Testing Machine Learning models on the original 30-sec 1000 file dataset

- Models Used
    - RandomForest - Ensemble Model that uses Bagging
    - XGBoost - Ensemble Model that uses boosting (This should perform best)

## Import Libraries

In [1]:
#Import Standard Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier

## Data Preprocessing

In [2]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [21]:
# Get Data Ready
data_file = "Data/features_3_sec.csv"
music_data = pd.read_csv(data_file)
music_data;

In [22]:
# Remove unnecessary Fields
music_data.drop(labels=["filename","length"],inplace=True, axis=1)
music_data;

In [23]:
label_mappings = dict(enumerate(music_data['label'].unique()))
label_mappings

{0: 'blues',
 1: 'classical',
 2: 'country',
 3: 'disco',
 4: 'hiphop',
 5: 'jazz',
 6: 'metal',
 7: 'pop',
 8: 'reggae',
 9: 'rock'}

In [24]:
#Converting Label Column to Numerical Field
for k, v in label_mappings.items():
    music_data.loc[(music_data['label'] == v),'label_code'] = k
    
music_data

,chroma_stft_mean,chroma_stft_var,rms_mean,rms_var,spectral_centroid_mean,spectral_centroid_var,spectral_bandwidth_mean,spectral_bandwidth_var,rolloff_mean,rolloff_var,...,mfcc17_mean,mfcc17_var,mfcc18_mean,mfcc18_var,mfcc19_mean,mfcc19_var,mfcc20_mean,mfcc20_var,label,label_code
0,0.335406,0.091048,0.130405,0.003521,1773.065032,167541.630869,1972.744388,117335.771563,3714.560359,1.080790e+06,...,-3.241280,36.488243,0.722209,38.099152,-5.050335,33.618073,-0.243027,43.771767,blues,0.0
1,0.343065,0.086147,0.112699,0.001450,1816.693777,90525.690866,2010.051501,65671.875673,3869.682242,6.722448e+05,...,-6.055294,40.677654,0.159015,51.264091,-2.837699,97.030830,5.784063,59.943081,blues,0.0
2,0.346815,0.092243,0.132003,0.004620,1788.539719,111407.437613,2084.565132,75124.921716,3997.639160,7.907127e+05,...,-1.768610,28.348579,2.378768,45.717648,-1.938424,53.050835,2.517375,33.105122,blues,0.0
3,0.363639,0.086856,0.132565,0.002448,1655.289045,111952.284517,1960.039988,82913.639269,3568.300218,9.216524e+05,...,-3.841155,28.337118,1.218588,34.770935,-3.580352,50.836224,3.630866,32.023678,blues,0.0
4,0.335579,0.088129,0.143289,0.001701,1630.656199,79667.267654,1948.503884,60204.020268,3469.992864,6.102111e+05,...,0.664582,45.880913,1.689446,51.363583,-3.392489,26.738789,0.536961,29.146694,blues,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,0.349126,0.080515,0.050019,0.000097,1499.083005,164266.886443,1718.707215,85931.574523,3015.559458,8.479527e+05,...,-9.094270,38.326839,-4.246976,31.049839,-5.625813,48.804092,1.818823,38.966969,rock,9.0
9986,0.372564,0.082626,0.057897,0.000088,1847.965128,281054.935973,1906.468492,99727.037054,3746.694524,1.170890e+06,...,-12.375726,66.418587,-3.081278,54.414265,-11.960546,63.452255,0.428857,18.697033,rock,9.0
9987,0.347481,0.089019,0.052403,0.000701,1346.157659,662956.246325,1561.859087,138762.841945,2442.362154,2.602871e+06,...,-2.524483,21.778994,4.809936,25.980829,1.775686,48.582378,-0.299545,41.586990,rock,9.0
9988,0.387527,0.084815,0.066430,0.000320,2084.515327,203891.039161,2018.366254,22860.992562,4313.266226,4.968878e+05,...,-5.363541,17.209942,6.462601,21.442928,2.354765,24.843613,0.675824,12.787750,rock,9.0
9989,0.369293,0.086759,0.050524,0.000067,1634.330126,411429.169769,1867.422378,119722.211518,3462.042142,1.517016e+06,...,-11.598399,58.983097,-0.178517,55.761299,-6.903252,39.485901,-3.412534,31.727489,rock,9.0

In [25]:
music_data[['label','label_code']]

      label  label_code
0     blues         0.0
1     blues         0.0
2     blues         0.0
3     blues         0.0
4     blues         0.0
...     ...         ...
9985   rock         9.0
9986   rock         9.0
9987   rock         9.0
9988   rock         9.0
9989   rock         9.0

[9990 rows x 2 columns]

In [26]:
# Split data into train/test datasets
from sklearn.model_selection import train_test_split

## Create Models

### Random Forest (87.45% Accuracy)

#### Models Ran
 - Default Parameters (n_estimators=100, criterion=gini)
 - Accuracy (n_estimators = 100, criterion = gini) = 0.8635301968635302 
 - Accuracy (n_estimators = 1000, criterion = gini) = 0.8745412078745413 - Best
 - Accuracy (n_estimators = 10,000, criterion = gini) = 0.8702035368702036
 - Accuracy (n_estimators = 1000, criterion = entropy) = 0.8732065398732065
 - Accuracy (n_estimators = 100, criterion = entropy) = 0.8625291958625292
 - Accuracy (n_estimators = 100, criterion = log loss) = 0.8668668668668669
 - Accuracy (n_estimators = 1000, criterion = log loss) = 0.8705372038705372

 - Classification Report for best model
                precision    recall  f1-score   support

       blues       0.88      0.88      0.88       301
   classical       0.92      0.96      0.94       310
     country       0.80      0.85      0.83       306
       disco       0.85      0.90      0.88       281
      hiphop       0.93      0.88      0.90       324
        jazz       0.82      0.89      0.85       281
       metal       0.89      0.93      0.91       292
         pop       0.91      0.90      0.90       289
      reggae       0.89      0.88      0.88       300
        rock       0.86      0.70      0.77       313

    accuracy                           0.87      2997
   macro avg       0.87      0.88      0.87      2997
weighted avg       0.88      0.87      0.87      2997

In [39]:
# Create Random Forest Model
# Default Parameters (n_estimators=100, criterion='gini'): Accuracy = 0.8635301968635302 
# n_estimators = 1000: Accuracy = 0.8735402068735402
# n_estimators = 10,000: Accuracy = 0.8702035368702036
ml_randomforest = RandomForestClassifier(n_estimators=1000)

# Train Random Forest
# Create X (Features)
rfX = music_data.drop(["label", "label_code"], axis=1)

# Create Y (Labels)
rfY = music_data['label']

rfX_train, rfX_test, rfY_train, rfY_test = train_test_split(rfX, rfY, test_size=0.3)
ml_randomforest.fit(rfX_train, rfY_train)

#ml_randomforest.score(rfX_train, rfY_train)

ml_randomforest.score(rfX_test, rfY_test)

0.8745412078745413

In [40]:
rf_preds = ml_randomforest.predict(rfX_test)

print(classification_report(rfY_test, rf_preds))

              precision    recall  f1-score   support

       blues       0.88      0.88      0.88       301
   classical       0.92      0.96      0.94       310
     country       0.80      0.85      0.83       306
       disco       0.85      0.90      0.88       281
      hiphop       0.93      0.88      0.90       324
        jazz       0.82      0.89      0.85       281
       metal       0.89      0.93      0.91       292
         pop       0.91      0.90      0.90       289
      reggae       0.89      0.88      0.88       300
        rock       0.86      0.70      0.77       313

    accuracy                           0.87      2997
   macro avg       0.87      0.88      0.87      2997
weighted avg       0.88      0.87      0.87      2997

### XGBoost (89.95% Accuracy)

#### Key for XGBoost Labels
 0.0 (blues)
 1.0 (classical)
 2.0 (country)
 3.0 (disco)
 4.0 (hiphop)
 5.0 (jazz)
 6.0 (metal)
 7.0 (pop)
 8.0 (reggae)
 9.0 (rock)
 

#### Models Ran

- n_estimators=100, max_depth=6, learning_rate=0.3: 0.8885552218885552 (default)
- n_estimators=100, max_depth=3, learning_rate=0.1: 0.7941274607941274
- n_estimators=1000, max_depth=3, learning_rate=0.1: 0.8978978978978979
- n_estimators=1000, max_depth=6, learning_rate=0.1: 0.8995662328995663 - Best
- n_estimators=10000, max_depth=3, learning_rate=0.1: 0.8972305638972305
- n_estimators=1000, max_depth=6, learning_rate=0.3: 0.8958958958958959

Best Classification Report
              precision    recall  f1-score   support

         0.0       0.91      0.90      0.90       278
         1.0       0.93      0.95      0.94       322
         2.0       0.86      0.88      0.87       311
         3.0       0.84      0.92      0.87       277
         4.0       0.91      0.89      0.90       299
         5.0       0.89      0.91      0.90       299
         6.0       0.93      0.94      0.93       280
         7.0       0.94      0.90      0.92       316
         8.0       0.92      0.88      0.90       326
         9.0       0.87      0.84      0.86       289

    accuracy                           0.90      2997
   macro avg       0.90      0.90      0.90      2997
weighted avg       0.90      0.90      0.90      2997

In [51]:
# Create and train XGBoost model w/ default parameters
ml_xgboost = xgb.XGBClassifier(n_estimators=1000, max_depth=6, learning_rate=0.3)

# Train XGBoost - Looks like XGBoost doesn't work with categorical data only numerical
# Create X (Features)
xgbX = music_data.drop(["label", "label_code"], axis=1)

# Create Y (Labels)
xgbY = music_data['label_code']

xgbX_train, xgbX_test, xgbY_train, xgbY_test = train_test_split(xgbX, xgbY, test_size=0.3)
ml_xgboost.fit(xgbX_train, xgbY_train)

xgb_preds = ml_xgboost.predict(xgbX_test)

ml_xgboost.score(xgbX_test, xgbY_test)

0.8958958958958959

In [50]:
print(classification_report(xgbY_test, xgb_preds))

              precision    recall  f1-score   support

         0.0       0.91      0.90      0.90       278
         1.0       0.93      0.95      0.94       322
         2.0       0.86      0.88      0.87       311
         3.0       0.84      0.92      0.87       277
         4.0       0.91      0.89      0.90       299
         5.0       0.89      0.91      0.90       299
         6.0       0.93      0.94      0.93       280
         7.0       0.94      0.90      0.92       316
         8.0       0.92      0.88      0.90       326
         9.0       0.87      0.84      0.86       289

    accuracy                           0.90      2997
   macro avg       0.90      0.90      0.90      2997
weighted avg       0.90      0.90      0.90      2997